version: '2'

services:
   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     privileged: true

   wordpress:
     depends_on:
       - db
     # image: wordpress:latest
     image: wp2:autumn
     ports:
       - "8000:80"
     restart: always
     working_dir: /var/www/html
     volumes:
       - /Users/user/develop/hl_blog_2/:/var/www/html/
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
     privileged: true
     # command: chmod a+rwx wp-content
volumes:
    db_data:
